### ISSUE TITLE
Bugs in the code

### ISSUE THREAD

**Issue by JunwenBai** [nikkou/latent-subspaces#1]
In the file "csvae_toy/csvae_toy.ipynb", there are some bugs in the function q_zw(), where "z_logvar = self.mu_x_to_z(intermediate)" should be corrected as "z_logvar = self.logvar_x_to_z(intermediate)".

**Comment by alexlyzhov** [comment]
True, thanks for pointing this out! I hope I'll put the code in a better shape next month.
